### PR TITLE
Adding schematic

### PR DESCRIPTION
**Pull request by kg333**
This adds a schematic matching the "Connections" section of the README.

Note that either config.h needs to be updated to reflect GPIO15 as listed in the "Connections" section, or the diagram will need to updated when #5 is merged.

### CODE REVIEW

**Comment by fiservedpi** [comment]
Just one quick question that sounds dumb many of the lines on the schematic are crossing which ones need to be connected rather that are just crossing in the photo

**Comment by kg333** [comment]
Lines that cross do not connect unless there is a dot at the intersection.  For example, J1-7 does not connect to J1-4, but does connect to U2-3.

**Comment by fiservedpi** [comment]
Great that really helps I wired it up today but will have to go back and do it again.

**Comment by johnboiles** [comment]
Solid, thank you! Do you have the original schematic file in case we want to update the diagram? I just updated my version of this circuit to include a voltage divider to ADC so that I can read the battery voltage directly (and maybe sleep the ESP if the battery gets too low).

**Comment by kg333** [comment]
No problem; I'll update the source to match #5 and put in a new PR.

**Comment by kg333** [comment]
Opened #11 for sources and update.

**Pull request merged**
